settings:
  alt_screen: true
  keymap:
    left: m
    right: i
    up: e
    down: n
    bookmark_set: b
    preview_scroll_up: E
    preview_scroll_down: N
  actions:
    archive:
      key: "alt+z"
      refresh: true
      clear_selection: true
  bookmarks:
    h: '~/'
    d: '~/Downloads'
    p: '~/projects'
